AWSTemplateFormatVersion: 2010-09-09
Parameters:
  VpcId:
    Type: String
    Default: ""
Conditions:
  UseVpc: !Equals [!Ref VpcId, '']
Resources:
  Network:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: vpc.yaml
    Condition: UseVpc
