AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: S3 Bucket with automatic cleanup on delete
Resources:
  Bucket:
    Type: AWS::S3::Bucket
    Properties:
      VersioningConfiguration:
        Status: Suspended
      LifecycleConfiguration:
        Rules:
        - ExpirationInDays: 30
          Status: Enabled
        - NoncurrentVersionExpirationInDays: 1
          Status: Disabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
        - ServerSideEncryptionByDefault:
            SSEAlgorithm: AES256
  EmptyBucketLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.7
      Handler: index.handler
      Policies:
      - Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
            - s3:List*
            - s3:DeleteObject
            - s3:DeleteObjectVersion
            Resource:
            - !Sub ${Bucket.Arn}
            - !Sub ${Bucket.Arn}/*
      InlineCode: |
          import boto3
          import cfnresponse

          s3 = boto3.resource('s3')

          def empty_s3(payload):
              bucket = s3.Bucket(payload['BucketName'])
              bucket.object_versions.all().delete()
              return {}

          def handler(event, context):
              try:
                  if event['RequestType'] in ['Delete']:
                      # clear bucket contents
                      cfnresponse.send(event, context, cfnresponse.SUCCESS,
                                       empty_s3(event['ResourceProperties']))
                  else:
                      # do nothing
                      cfnresponse.send(event, context, cfnresponse.SUCCESS,
                                       {}, event['LogicalResourceId'])
              except Exception as e:
                  cfnresponse.send(event, context, "FAILED", {"Message": str(e)})
  EmptyBucket:
    Type: Custom::EmptyBucket
    Properties:
      ServiceToken: !GetAtt EmptyBucketLambda.Arn
      BucketName: !Ref Bucket
Outputs:
  Name:
    Value: !Ref Bucket
