AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Create image repositories
Parameters:
  RepositoryList:
    Type: CommaDelimitedList
  RepositoryRetain:
    Type: String
    Default: false
    AllowedValues:
    - true
    - false
Resources:
  EcrCreateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: WriteCloudwatchLogs
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - 'arn:aws:logs:*:*:*'
      - PolicyName: RepositoryAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - ecr:DescribeRepositories
            - ecr:CreateRepository
            - ecr:DeleteRepository
            Resource: '*'
  EcrCreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: ecr_create.handler
      Role: !GetAtt EcrCreateRole.Arn
      Timeout: 60
      CodeUri: src
  EcrCreate:
    Type: Custom::EcrCreate
    Properties:
      ServiceToken: !GetAtt EcrCreateLambda.Arn
      RepositoryList: !Join [',', !Ref RepositoryList]
      Retain: !Ref RepositoryRetain
Outputs:
  RepositoryList:
    Value: !Join [',', !Ref RepositoryList]
