AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31
Description: Create image repositories
Parameters:
  EnvironmentName:
    Type: String
  RepositoryPathList:
    Type: CommaDelimitedList
  RepositoryRetain:
    Type: String
    Default: false
    AllowedValues:
    - true
    - false
Resources:
  EcrCreateRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: WriteCloudwatchLogs
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource:
            - 'arn:aws:logs:*:*:*'
      - PolicyName: RepositoryAccess
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
            - ecr:DescribeRepositories
            - ecr:CreateRepository
            - ecr:DeleteRepository
            Resource: '*'
  EcsTaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ecs-tasks.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
      - PolicyName: AmazonECSTaskExecutionRolePolicy
        PolicyDocument:
          Statement:
          - Effect: Allow
            Action:
            - ecr:GetAuthorizationToken
            - ecr:BatchCheckLayerAvailability
            - ecr:GetDownloadUrlForLayer
            - ecr:BatchGetImage
            Resource: '*'
          - Effect: Allow
            Action:
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: '*'
  EcrCreateLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: python3.8
      Handler: ecr_create.handler
      Role: !GetAtt EcrCreateRole.Arn
      Timeout: 60
      CodeUri: src
  EcrCreate:
    Type: Custom::EcrCreate
    Properties:
      ServiceToken: !GetAtt EcrCreateLambda.Arn
      EnvironmentName: !Ref EnvironmentName
      RepositoryPathList: !Join [',', !Ref RepositoryPathList]
      Retain: !Ref RepositoryRetain
Outputs:
  #RepositoryPathList:
  #  Value: !GetAtt EcrCreate.RepositoryPathList
  #EnvironmentName:
  #  Value: !GetAtt EcrCreate.EnvironmentName
  EcrCreate:
    Value: !GetAtt EcrCreate.EcrCreate
  EcrDelete:
    Value: !GetAtt EcrCreate.EcrDelete
  EcsTaskExecutionRole:
    Value: !GetAtt EcsTaskExecutionRole.Arn
