AWSTemplateFormatVersion: 2010-09-09
Description: Create KMSKey for use in Stack
Parameters:
  DockerHubUsername:
    Type: String
    NoEcho : true
  DockerHubPassword:
    Type: String
    NoEcho : true
Conditions:
  DockerHubSet:
    !And
    - !Not [!Equals [!Ref DockerHubUsername, '']]
    - !Not [!Equals [!Ref DockerHubPassword, '']]
Resources:
  KMSKey:
    Type: AWS::KMS::Key
    Properties:
      EnableKeyRotation: true
      KeyPolicy:
        Statement:
        - Sid: Enable IAM User Permissions
          Effect: Allow
          Action: kms:*
          Resource: "*"
          Principal:
            AWS: !Sub arn:aws:iam::${AWS::AccountId}:root
  KMSAlias:
    Type: AWS::KMS::Alias
    Properties:
      AliasName: !Sub alias/${AWS::StackName}
      TargetKeyId: !Ref KMSKey
  DockerHubSecret:
    Type: AWS::SecretsManager::Secret
    Condition: DockerHubSet
    Properties:
      KmsKeyId: !GetAtt KMSKey.Arn
      SecretString: !Sub 
      - '{"username": "${DockerHubUsername}" ,"password": "${DockerHubPassword}"}'
      - { DockerHubUsername: !Ref DockerHubUsername, DockerHubPassword: !Ref DockerHubPassword }
Outputs:
  KMSKeyArn:
    Value: !GetAtt KMSKey.Arn
  DockerHubSecretArn:
    Value: !If [DockerHubSet, !Ref DockerHubSecret, '']
